### ISSUE TITLE
Compiler error with macro STRINGIFY

### ISSUE THREAD

**Issue by playgithub** [jim-dale/WakeOnLan#1]
```
1>------ Build started: Project: WakeOnLan, Configuration: Debug x64 ------
1>WakeOnLan.cpp
1>\path\to\WakeOnLan\src\AppMetadata.h(16,30): warning C4003: not enough arguments for function-like macro invocation 'STRINGIFY2'
1>\path\to\WakeOnLan\src\AppMetadata.h(16,49): error C2059: syntax error: ';'
1>Done building project "WakeOnLan.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

```C++
static const char* GitHash = STRINGIFY(BUILDNUM);
```
be fixed as a workaround
```C++
static const char* GitHash = STRINGIFY("BUILDNUM");
```

Please check it

**Comment by jim-dale** [comment]
`BUILDNUM` is defined on the command line when compiling. Look at the **WakeOnLan**->**Properties** under **Configuration properties** -> **C/C++** -> **Preprocessor**, you will find
`BUILDNUM=$(BUILD_BUILDNUMBER)`
This requires that there is an environment variable called `BUILD_BUILDNUMBER` that defines some text that gets used when the user types `WakeOnLan -v` to get the version information.

When compiling in Visual Studio:
- Close Visual Studio
- At a Windows command prompt type `SETX BUILD_BUILDNUMBER Internal` to define the environment variable to the text `Internal`. This can be any text you like.
- Start Visual Studio and compile the project.

The automated build (`azure-pipelines.yml`) sets this property to the value `$(Build.SourceVersion)`. This embeds the exact Git revision in the executable which the user can see when running `WakeOnLan -v`

**Comment by playgithub** [comment]
What about give `BUILDNUM` a default value? So that no default compile error.

**Comment by jim-dale** [comment]
`BUILDNUM` when set is a string and you can't do string comparisons with the C/C++ pre-processor.
When the env var `BUILD_BUILDNUMBER` is not set, the pre-processor symbol `BUILDNUM` is still defined.
The pre-processor can only test for defined of undefined (for strings) i.e. #ifdef or #ifundef
You can't therefore set a default value. The header does attempt to set a default value but doesn't work because 'BUILDNUM' is always defined regardless of whether `BUILD_BUILDNUMBER' is set or not.

**Comment by playgithub** [comment]
> `BUILDNUM` when set is a string and you can't do string comparisons with the C/C++ pre-processor.
> When the env var `BUILD_BUILDNUMBER` is not set, the pre-processor symbol `BUILDNUM` is still defined.
> The pre-processor can only test for defined of undefined (for strings) i.e. #ifdef or #ifundef
> You can't therefore set a default value. The header does attempt to set a default value but doesn't work because 'BUILDNUM' is always defined regardless of whether `BUILD_BUILDNUMBER' is set or not.

A workaround

```C++
#include <iostream>

#define DO_QUOTE(X) #X
#define QUOTE(X) DO_QUOTE(X)

#define DO_EXPAND(VAL) VAL ## 1
#define EXPAND(VAL) DO_EXPAND(VAL)

#define AAA

int main()
{

#if !defined(AAA) || (EXPAND(AAA) == 1)
    std::cout << "not defined or empty" << std::endl;
#else
    std::cout << "defined (" << QUOTE(AAA) << ")" << std::endl;

#endif

    return 0;
}
```
